name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # frontend:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./frontend/clean-board
  #   
  #   steps:
  #   - uses: actions/checkout@v4
  #   
  #   - name: Setup Bun
  #     uses: oven-sh/setup-bun@v2
  #     with:
  #       bun-version: latest
  #   
  #   - name: Install dependencies
  #     run: bun install
  #   
  #   - name: Run linter
  #     run: bun run lint
  #   
  #   - name: Run formatter check
  #     run: bun run format --dry-run
  #   
  #   - name: Build
  #     run: bun run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest
    
    - name: Run ruff linter
      run: ruff check src/
    
    - name: Run ruff formatter
      run: ruff format --check src/
    
    - name: Run tests
      run: pytest src/ -v || echo "No tests found, skipping"